### ISSUE TITLE
`pdfalyzer` does not work with `pypdf` 6.6.0

### ISSUE THREAD

**Issue by daeho-ro** [michelcrypt4d4mus/pdfalyzer#32]
Hello, recently `pypdf` pushed a new version 6.6.0 which contains security fix.
- https://github.com/py-pdf/pypdf/security/advisories/GHSA-4f6g-68pf-7vhv

So, update and run `pdfalyzer` but failed with an error.

```
  Traceback (most recent call last):
    File "/home/linuxbrew/.linuxbrew/Cellar/pdfalyzer/1.17.11_1/bin/pdfalyze", line 3, in <module>
      from pdfalyzer import pdfalyze
    File "/home/linuxbrew/.linuxbrew/Cellar/pdfalyzer/1.17.11_1/libexec/lib/python3.14/site-packages/pdfalyzer/__init__.py", line 31, in <module>
      from pdfalyzer.output.pdfalyzer_presenter import PdfalyzerPresenter
    File "/home/linuxbrew/.linuxbrew/Cellar/pdfalyzer/1.17.11_1/libexec/lib/python3.14/site-packages/pdfalyzer/output/pdfalyzer_presenter.py", line 30, in <module>
      from pdfalyzer.pdfalyzer import Pdfalyzer
    File "/home/linuxbrew/.linuxbrew/Cellar/pdfalyzer/1.17.11_1/libexec/lib/python3.14/site-packages/pdfalyzer/pdfalyzer.py", line 21, in <module>
      from pdfalyzer.font_info import FontInfo
    File "/home/linuxbrew/.linuxbrew/Cellar/pdfalyzer/1.17.11_1/libexec/lib/python3.14/site-packages/pdfalyzer/font_info.py", line 5, in <module>
      from pypdf._cmap import build_char_map, prepare_cm
  ImportError: cannot import name 'build_char_map' from 'pypdf._cmap' (/home/linuxbrew/.linuxbrew/Cellar/pdfalyzer/1.17.11_1/libexec/lib/python3.14/site-packages/pypdf/_cmap.py)
```

`pypdf` removes `build_char_map` and change their code a bit, so this makes they are not compatible.

Can you check?
Thanks,

**Comment by daeho-ro** [comment]
It is working now, Thanks!
